/*
 * Jupiter API v6
 *
 * The core of [jup.ag](https://jup.ag). Easily get a quote and swap through Jupiter API.  ### Rate Limit We update our rate limit from time to time depending on the load of our servers. We recommend running your own instance of the API if you want to have high rate limit, here to learn how to run the [self-hosted API](https://station.jup.ag/docs/apis/self-hosted).  ### API Wrapper - Typescript [@jup-ag/api](https://github.com/jup-ag/jupiter-quote-api-node)  ### Data types - Public keys are base58 encoded strings - raw data such as Vec<u8\\> are base64 encoded strings
 *
 * API version: 6.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package jupiter

type SwapRequest struct {
	// The user public key.
	UserPublicKey string `json:"userPublicKey"`
	// Default is true. If true, will automatically wrap/unwrap SOL. If false, it will use wSOL token account.  Will be ignored if `destinationTokenAccount` is set because the `destinationTokenAccount` may belong to a different user that we have no authority to close.
	WrapAndUnwrapSol bool `json:"wrapAndUnwrapSol,omitempty"`
	// Default is true. This enables the usage of shared program accountns. That means no intermediate token accounts or open orders accounts need to be created for the users. But it also means that the likelihood of hot accounts is higher.
	UseSharedAccounts bool `json:"useSharedAccounts,omitempty"`
	// Fee token account, same as the output token for ExactIn and as the input token for ExactOut, it is derived using the seeds = [\"referral_ata\", referral_account, mint] and the `REFER4ZgmyYx9c6He5XfaTMiGfdLwRnkV4RPp9t9iF3` referral contract (only pass in if you set a feeBps and make sure that the feeAccount has been created).
	FeeAccount string `json:"feeAccount,omitempty"`
	// The compute unit price to prioritize the transaction, the additional fee will be `computeUnitLimit (1400000) * computeUnitPriceMicroLamports`. If `auto` is used, Jupiter will automatically set a priority fee and it will be capped at 5,000,000 lamports / 0.005 SOL.
	ComputeUnitPriceMicroLamports AnyOfSwapRequestComputeUnitPriceMicroLamports `json:"computeUnitPriceMicroLamports,omitempty"`
	// \\* PriorityFeeWithMaxLamports is impossible to be typed. Prioritization fee lamports paid for the transaction in addition to the signatures fee. Mutually exclusive with compute_unit_price_micro_lamports. If `auto` is used, Jupiter will automatically set a priority fee and it will be capped at 5,000,000 lamports / 0.005 SOL.
	PrioritizationFeeLamports AnyOfSwapRequestPrioritizationFeeLamports `json:"prioritizationFeeLamports,omitempty"`
	// Default is false. Request a legacy transaction rather than the default versioned transaction, needs to be paired with a quote using asLegacyTransaction otherwise the transaction might be too large.
	AsLegacyTransaction bool `json:"asLegacyTransaction,omitempty"`
	// Default is false. This is useful when the instruction before the swap has a transfer that increases the input token amount. Then, the swap will just use the difference between the token ledger token amount and post token amount.
	UseTokenLedger bool `json:"useTokenLedger,omitempty"`
	// Public key of the token account that will be used to receive the token out of the swap. If not provided, the user's ATA will be used. If provided, we assume that the token account is already initialized.
	DestinationTokenAccount string `json:"destinationTokenAccount,omitempty"`
	// When enabled, it will do a swap simulation to get the compute unit used and set it in ComputeBudget's compute unit limit. This will increase latency slightly since there will be one extra RPC call to simulate this. Default is `false`.
	DynamicComputeUnitLimit bool `json:"dynamicComputeUnitLimit,omitempty"`
	// When enabled, it will not do any rpc calls check on user's accounts. Enable it only when you already setup all the accounts needed for the trasaction, like wrapping or unwrapping sol, destination account is already created.
	SkipUserAccountsRpcCalls bool `json:"skipUserAccountsRpcCalls,omitempty"`
	// The program authority id [0;7], load balanced across the available set by default
	ProgramAuthorityId int32 `json:"programAuthorityId,omitempty"`
	// Default is false. Enabling it would reduce use an optimized way to open WSOL that reduce compute unit.
	AllowOptimizedWrappedSolTokenAccount bool                        `json:"allowOptimizedWrappedSolTokenAccount,omitempty"`
	QuoteResponse                        *QuoteResponse              `json:"quoteResponse"`
	DynamicSlippage                      *SwapRequestDynamicSlippage `json:"dynamicSlippage,omitempty"`
	// Optional. When passed in, Swap object will be returned with your desired slots to epxiry.
	BlockhashSlotsToExpiry float64 `json:"blockhashSlotsToExpiry,omitempty"`
	// Optional. Default to false. Request Swap object to be returned with the correct blockhash prior to Agave 2.0.
	CorrectLastValidBlockHeight bool `json:"correctLastValidBlockHeight,omitempty"`
}
